"""Post-calculation action for automatic spectrum extraction.

Provides a bundled Python script that can be attached to OrcaFlex models
as a post-calculation action. When the simulation completes, this script
automatically extracts time histories and computes spectra, saving them
to .npz files alongside the .sim file.

This enables "fire-and-forget" batch processing where the spectral analysis
is done during simulation, eliminating the need for post-processing with
an OrcaFlex licence.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

# The post-calculation script template
# This script is embedded in OrcaFlex models and runs after simulation
# NOTE: Use doubled braces {{}} for literal braces in the output script,
# single braces {} for .format() placeholders
POST_CALC_SCRIPT = '''
"""Spectraflex post-calculation action script.

This script is automatically executed by OrcaFlex after simulation completion.
It extracts time histories, computes cross-spectra, and saves to .npz file.

Auto-generated by spectraflex.orcaflex.post_calc
"""

import numpy as np
from scipy import signal

# Configuration (set by attach_post_calc)
RESULTS_SPEC = {results_spec}
NPERSEG = {nperseg}
NOVERLAP = {noverlap}
WINDOW = "{window}"
WAVE_POSITION = {wave_position}


def Execute(info):
    """OrcaFlex post-calculation action entry point."""
    model = info.Model

    # Get analysis period (skip build-up)
    t_start = model.general.StageDuration[0]
    t_end = t_start + model.general.StageDuration[1]

    try:
        import OrcFxAPI as ofx
        period = ofx.SpecifiedPeriod(t_start, t_end)
    except Exception:
        # Fallback for older API versions
        period = (t_start, t_end)

    # Get sample interval
    sample_times = model.environment.SampleTimes(period)
    dt = float(sample_times[1] - sample_times[0])
    fs = 1.0 / dt

    # Extract wave elevation
    try:
        import OrcFxAPI as ofx
        wave_env = ofx.oeEnvironment(*WAVE_POSITION)
    except Exception:
        wave_env = WAVE_POSITION

    wave = np.array(model.environment.TimeHistory("Elevation", period, wave_env))

    # Extract response time histories
    variable_names = []
    responses = []

    for spec in RESULTS_SPEC:
        obj = model[spec["object"]]
        var_name = spec["variable"]
        label = spec.get("label", spec["object"] + "_" + var_name)
        variable_names.append(label)

        # Build ObjectExtra if needed
        if "arclength" in spec and spec["arclength"] is not None:
            try:
                import OrcFxAPI as ofx
                obj_extra = ofx.oeArcLength(spec["arclength"])
            except Exception:
                obj_extra = spec["arclength"]
        else:
            obj_extra = None

        th = np.array(obj.TimeHistory(var_name, period, obj_extra))
        responses.append(th)

    responses = np.column_stack(responses)  # (n_time, n_var)
    n_var = len(variable_names)

    # Compute spectra using Welch's method
    noverlap = NOVERLAP if NOVERLAP is not None else NPERSEG // 2

    # Input auto-spectrum
    f, Sxx = signal.welch(
        wave, fs=fs, window=WINDOW, nperseg=NPERSEG,
        noverlap=noverlap, detrend="constant", scaling="density"
    )

    # Only positive frequencies (excluding DC)
    pos_mask = f > 0
    f = f[pos_mask]
    Sxx = Sxx[pos_mask]
    n_freq = len(f)

    # Output spectra and cross-spectra
    Syy = np.zeros((n_freq, n_var))
    Sxy = np.zeros((n_freq, n_var), dtype=np.complex128)

    for i in range(n_var):
        resp = responses[:, i]

        # Output auto-spectrum
        _, syy_full = signal.welch(
            resp, fs=fs, window=WINDOW, nperseg=NPERSEG,
            noverlap=noverlap, detrend="constant", scaling="density"
        )
        Syy[:, i] = syy_full[pos_mask]

        # Cross-spectrum
        _, sxy_full = signal.csd(
            wave, resp, fs=fs, window=WINDOW, nperseg=NPERSEG,
            noverlap=noverlap, detrend="constant", scaling="density"
        )
        Sxy[:, i] = sxy_full[pos_mask]

    # Save to .npz file alongside the .sim
    sim_path = info.ModelFileName
    if sim_path.endswith(".sim"):
        output_path = sim_path[:-4] + "_spectra.npz"
    else:
        output_path = sim_path + "_spectra.npz"

    np.savez(
        output_path,
        frequency=f,
        Sxx=Sxx,
        Syy=Syy,
        Sxy=Sxy,
        variable_names=np.array(variable_names, dtype=object),
        dt=dt,
        nperseg=NPERSEG,
        noverlap=noverlap,
        window=WINDOW,
    )

    info.Log("spectraflex: Saved spectra to " + output_path)
'''


def get_post_calc_script(
    results: list[dict[str, Any]],
    nperseg: int = 1024,
    noverlap: int | None = None,
    window: str = "hann",
    wave_position: tuple[float, float, float] = (0.0, 0.0, 0.0),
) -> str:
    """Get the post-calculation script with configured parameters.

    Parameters
    ----------
    results : list of dict
        Result specifications, each with keys:
        - object: str, OrcaFlex object name
        - variable: str, variable name
        - arclength: float, optional, arc length for line objects
        - label: str, optional, friendly name
    nperseg : int, optional
        FFT segment length, default 1024.
    noverlap : int, optional
        Overlap points, default nperseg // 2.
    window : str, optional
        Window function, default "hann".
    wave_position : tuple, optional
        (x, y, z) for wave elevation extraction, default (0, 0, 0).

    Returns
    -------
    str
        Python script ready to be embedded in OrcaFlex model.
    """
    return POST_CALC_SCRIPT.format(
        results_spec=repr(results),
        nperseg=nperseg,
        noverlap=repr(noverlap),
        window=window,
        wave_position=repr(wave_position),
    )


def attach_post_calc(
    template: str | Path,
    results: list[dict[str, Any]],
    output_path: str | Path | None = None,
    nperseg: int = 1024,
    noverlap: int | None = None,
    window: str = "hann",
    wave_position: tuple[float, float, float] = (0.0, 0.0, 0.0),
    action_name: str = "spectraflex_extract",
) -> Path:
    """Attach post-calculation action to an OrcaFlex model.

    Modifies the template .dat file to include a Python post-calculation
    action that automatically extracts spectra when simulations complete.

    Parameters
    ----------
    template : str or Path
        Path to the OrcaFlex model file (.dat).
    results : list of dict
        Result specifications for extraction.
    output_path : str or Path, optional
        Output path for modified model. If None, overwrites template.
    nperseg : int, optional
        FFT segment length, default 1024.
    noverlap : int, optional
        Overlap points.
    window : str, optional
        Window function, default "hann".
    wave_position : tuple, optional
        (x, y, z) for wave elevation.
    action_name : str, optional
        Name for the post-calc action, default "spectraflex_extract".

    Returns
    -------
    Path
        Path to the modified model file.

    Raises
    ------
    ImportError
        If OrcFxAPI is not available.
    """
    try:
        import OrcFxAPI as ofx
    except ImportError as e:
        raise ImportError(
            "OrcFxAPI is required to attach post-calculation actions. "
            "Install OrcFxAPI or manually add the script to your model."
        ) from e

    template = Path(template)
    if output_path is None:
        output_path = template
    else:
        output_path = Path(output_path)

    # Load model
    model = ofx.Model(str(template))

    # Get the script
    script = get_post_calc_script(
        results=results,
        nperseg=nperseg,
        noverlap=noverlap,
        window=window,
        wave_position=wave_position,
    )

    # Check if action already exists
    existing_actions = list(model.general.PostCalculationActionCount)
    action_exists = False
    action_index = len(existing_actions)

    for i in range(model.general.PostCalculationActionCount):
        if model.general.PostCalculationActionName[i] == action_name:
            action_exists = True
            action_index = i
            break

    # Add or update the post-calculation action
    if not action_exists:
        # Add new action
        model.general.PostCalculationActionCount = action_index + 1

    model.general.PostCalculationActionName[action_index] = action_name
    model.general.PostCalculationActionType[action_index] = "Python"
    model.general.PostCalculationActionEnabled[action_index] = True
    model.general.PostCalculationActionPythonScript[action_index] = script

    # Save model
    model.SaveData(str(output_path))

    return output_path


def write_standalone_script(
    output_path: str | Path,
    results: list[dict[str, Any]],
    nperseg: int = 1024,
    noverlap: int | None = None,
    window: str = "hann",
    wave_position: tuple[float, float, float] = (0.0, 0.0, 0.0),
) -> Path:
    """Write the post-calculation script to a standalone .py file.

    This can be useful for debugging or manual attachment to models.

    Parameters
    ----------
    output_path : str or Path
        Output file path.
    results : list of dict
        Result specifications.
    nperseg : int, optional
        FFT segment length.
    noverlap : int, optional
        Overlap points.
    window : str, optional
        Window function.
    wave_position : tuple, optional
        (x, y, z) for wave elevation.

    Returns
    -------
    Path
        Path to the written script file.
    """
    output_path = Path(output_path)
    script = get_post_calc_script(
        results=results,
        nperseg=nperseg,
        noverlap=noverlap,
        window=window,
        wave_position=wave_position,
    )
    output_path.write_text(script)
    return output_path
